In [11]:
!pip install loguru

from sklearn.decomposition import  KernelPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from data import prepare_data
from loguru import logger
import numpy as np
from sklearn import neighbors
from sklearn.model_selection import cross_validate
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.neighbors.nearest_centroid import NearestCentroid


In [ ]:
DATASET = 'CIFAR10'
# DATASET = 'MNIST'

SEED = 0
np.random.seed(SEED)  # to reproduce results (same randomness)
logger.add(f'{DATASET}_kpca_lda.log')  # log results (in .log)

if DATASET == 'MNIST':
    X_train, X_test, y_train, y_test = prepare_data(DATASET, apply_pca=False, train_samples=17000, test_samples=10000)
else:
    X_train, X_test, y_train, y_test = prepare_data(DATASET, apply_pca=False, train_samples=17000, test_samples=10000)

if DATASET == 'MNIST':
    kpca = KernelPCA(kernel="poly",n_components=87 , gamma=1, n_jobs=1) # MNIST
else:
    kpca = KernelPCA(kernel="rbf", degree=3, n_components=75 , gamma=.5, n_jobs=1) # CIFAR-10
    
X_kpca = kpca.fit_transform(X_train)
X_test = kpca.transform(X_test)
print(kpca)
print(X_kpca.shape)
DATASET = 'CIFAR10'
# DATASET = 'MNIST'

SEED = 0
np.random.seed(SEED)  # to reproduce results (same randomness)
logger.add(f'{DATASET}_kpca_lda.log')  # log results (in .log)

if DATASET == 'MNIST':
    X_train, X_test, y_train, y_test = prepare_data(DATASET, apply_pca=False, train_samples=17000, test_samples=10000)
else:
    X_train, X_test, y_train, y_test = prepare_data(DATASET, apply_pca=False, train_samples=17000, test_samples=10000)

if DATASET == 'MNIST':
    kpca = KernelPCA(kernel="poly",n_components=87 , gamma=1, n_jobs=1) # MNIST
else:
    kpca = KernelPCA(kernel="rbf", degree=3, n_components=75 , gamma=.5, n_jobs=1) # CIFAR-10
    
X_kpca = kpca.fit_transform(X_train)
X_test = kpca.transform(X_test)
print(kpca)
print(X_kpca.shape)

lda = LDA()
print (lda)

X_lda = lda.fit_transform(X_kpca,y_train)
X_test = lda.transform(X_test)
print(X_lda.shape)

KernelPCA(alpha=1.0, coef0=1, copy_X=True, degree=3, eigen_solver='auto',
          fit_inverse_transform=False, gamma=0.5, kernel='rbf',
          kernel_params=None, max_iter=None, n_components=75, n_jobs=1,
          random_state=None, remove_zero_eig=False, tol=0)
(17000, 75)


In [ ]:
#kNN classification
clf = neighbors.KNeighborsClassifier(n_neighbors=2)
clf.fit(X_lda, y_train)
print (clf)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')


In [ ]:
# training metrics
y_tr_pred = clf.predict(X_lda)
train_acc = accuracy_score(y_tr_pred, y_train)
train_conf_mat = confusion_matrix(y_train, y_tr_pred)

print(f'kNN Training Accuracy: {train_acc}')
print(f'Training Confusion Matrix: \n{train_conf_mat}', )

kNN Training Accuracy: 0.5929411764705882
Training Confusion Matrix: 
[[1696    0    0    0    0    0    0    0    0    0]
 [ 132 1567    0    0    0    0    0    0    0    0]
 [ 216  103 1425    0    0    0    0    0    0    0]
 [ 141  183  158 1236    0    0    0    0    0    0]
 [ 150  104  219  161 1077    0    0    0    0    0]
 [ 118  161  139  215  139  837    0    0    0    0]
 [ 141  148  225  202  190  166  665    0    0    0]
 [ 168  185  116  179  170  177  147  572    0    0]
 [ 236  169  120  111  111  119  109  117  618    0]
 [ 126  282   95  137   64  150   90  159  172  387]]


In [ ]:
# testing metrics
y_pred = clf.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)

print(f'kNN Trained Classifier (Testing) Accuracy: {test_acc}')
print(f'Confusion Matrix: \n{conf_mat}', )

kNN Trained Classifier (Testing) Accuracy: 0.113
Confusion Matrix: 
[[ 78   2  61  18  61   7 687   2  84   0]
 [  1   1   5   4   3   1 972   0  13   0]
 [ 88   6  90  25  85  10 654   2  40   0]
 [ 16   3  30   8  18   5 895   1  24   0]
 [ 70  11  86  39 101   9 619   2  63   0]
 [ 14   3  23   5  32   2 897   0  24   0]
 [ 30   6  46  21  91   4 765   0  37   0]
 [  5   2  15   3  20   1 926   0  28   0]
 [ 44   5  25  13  25   1 801   1  85   0]
 [  2   0   3   1   4   1 971   0  18   0]]


In [ ]:
#Nearest Centroid classification
classifier = NearestCentroid(shrink_threshold=.5)
classifier.fit(X_lda, y_train)
NearestCentroid(metric='euclidean', shrink_threshold=None)
print (classifier)


NearestCentroid(metric='euclidean', shrink_threshold=0.5)


In [ ]:
# training metrics
y_tr_pred = classifier.predict(X_lda)
train_acc = accuracy_score(y_tr_pred, y_train)
train_conf_mat = confusion_matrix(y_train, y_tr_pred)

print(f'Nearest Centroid Training Accuracy: {train_acc}')
print(f'Training Confusion Matrix: \n{train_conf_mat}', )

Nearest Centroid Training Accuracy: 0.143
Training Confusion Matrix: 
[[ 113   13   71   11   36   40   21 1286   73   32]
 [   1    3    1    2    5    6    3 1671    6    1]
 [  65    7  201   32   97   67   27 1204   27   17]
 [  13    5   19   14   25   39   18 1571    7    7]
 [  34   10   90   27  176  145   44 1150   22   13]
 [   7    3   15    6   25   40    4 1500    6    3]
 [  17    5   52   26   68   92   84 1369   15    9]
 [   4    3   13    5   11   32   12 1627    4    3]
 [  16   13   17    3   18   30   13 1396  169   35]
 [   1    1    1    2    1    5    0 1640    7    4]]


In [ ]:
# testing metrics
y_pred = classifier.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)

print(f'Nearest Centroid Trained Classifier (Testing) Accuracy: {test_acc}')
print(f'Confusion Matrix: \n{conf_mat}', )

Nearest Centroid Trained Classifier (Testing) Accuracy: 0.1219
Confusion Matrix: 
[[ 39   0  31   4  20 796   9  81  20   0]
 [  0   0   0   0   0 975   4  20   1   0]
 [ 33   0  64   2  48 775  17  54   7   0]
 [  4   0   3   3  13 948   6  21   2   0]
 [ 23   0  49  11  65 776  21  44  11   0]
 [  3   0   5   0  11 955   0  25   1   0]
 [  4   0  13   2  21 878  23  57   2   0]
 [  3   0   5   0   5 960   2  24   1   0]
 [  8   0   5   1   7 857   3  72  46   1]
 [  0   0   0   0   2 990   1   7   0   0]]
